#!/usr/bin/env bash

echo "0 3 * * * geoipupdate -f /var/www/html/config/GeoIP.conf -d /var/www/html/var/cache/ip_data/ 2>&1 | tee -a /var/www/html/var/logs/mautic-geoipupdate.log" > /opt/mautic/cron/mautic-geoipupdate

chmod 0644 /opt/mautic/cron/mautic-geoipupdate

crontab /opt/mautic/cron/mautic-geoipupdate

chmod +x mautic_cron-updateifchanged.sh

/mautic_cron-updateifchanged.sh -j /opt/mautic/cron/mautic-geoipupdate > /var/www/html/var/logs/mautic-cron_install-cron.log

service cron start

# Copy the postfix self-signed certificate generated by the postfix container
update-ca-certificates

/entrypoint.sh

apache2-foreground
