#!/bin/bash

### This entrypoint script includes in the MAUTIC-WEB service the Cron Job for processing the import files in backgroud contact files
### To change the cron job execution time after deployment, change the value of the ./volumes/crontab/mautic-import to the desired value

# Fail on error
#set -e
#set -o pipefail

# Create the cron directory
mkdir -p /opt/mautic/cron

# Set up the cron job
echo "*/5 * * * * /usr/local/bin/php /var/www/html/bin/console mautic:import 2>&1 | tee -a /var/www/html/var/logs/mautic-import.log" > /opt/mautic/cron/mautic-import

chmod 0644 /opt/mautic/cron/mautic-import

crontab /opt/mautic/cron/mautic-import

chmod +x /mautic_cron-updateifchanged.sh

/mautic_cron-updateifchanged.sh -j /opt/mautic/cron/mautic-import > /var/www/html/var/logs/mautic-web_install-cron.log

# Start services
service cron start

# Copy the postfix self-signed certificate generated by the postfix container
update-ca-certificates

/entrypoint.sh

apache2-foreground
