#!/usr/bin/env bash

# Set non-interactive frontend
export DEBIAN_FRONTEND=noninteractive

if ! dpkg -l | grep -q geoipupdate; then
    echo "geoipupdate is not installed. Installing..."

    # Download the package
    curl -L -o /tmp/geoipupdate.deb https://github.com/maxmind/geoipupdate/releases/download/v7.1.0/geoipupdate_7.1.0_linux_amd64.deb

    # Install with dpkg and handle dependencies with apt
    dpkg -i /tmp/geoipupdate.deb

    # Clean up
    rm -f /tmp/geoipupdate.deb
fi

echo "0 3 * * * geoipupdate -f /var/www/html/config/GeoIP.conf -d /var/www/html/var/cache/prod/ip_data/ 2>&1 | tee -a /var/www/html/var/logs/mautic-geoipupdate.log" > /opt/mautic/cron/mautic-geoipupdate

chmod 0644 /opt/mautic/cron/mautic-geoipupdate

crontab /opt/mautic/cron/mautic-geoipupdate

chmod +x mautic_cron-updateifchanged.sh

/mautic_cron-updateifchanged.sh -j /opt/mautic/cron/mautic-geoipupdate > /var/www/html/var/logs/mautic-cron_install-cron.log

service cron start

# Copy the postfix self-signed certificate generated by the postfix container
update-ca-certificates


/entrypoint.sh

apache2-foreground
